# Generated by Django 6.1 on 2026-09-08 08:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_studentappeal_satisfaction_poll_sent_and_more'),
        ('finance', '0009_refine_cashbox_branches'),
        ('organizations', '0004_telegramnotificationsetting_support_contact_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Dars sanasi')),
                ('hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name="O'tilgan soat")),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='1 soat dars narxi')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Jami hisoblangan summa')),
                ('is_substitution', models.BooleanField(default=False, verbose_name="O'rinbosarlik (zamen) darsimi?")),
                ('substitution_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zamen sababi')),
                ('note', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha izoh")),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_teacher_works', to=settings.AUTH_USER_MODEL, verbose_name='Kiritgan xodim (filial rahbari)')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_work_logs', to='academics.group', verbose_name='Guruh')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('original_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_work_logs', to=settings.AUTH_USER_MODEL, verbose_name="Asl o'qituvchi (zamen bo'lsa)")),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to=settings.AUTH_USER_MODEL, verbose_name="Dars o'tgan o'qituvchi")),
            ],
            options={
                'verbose_name': "O'qituvchi dars qaydnomasi",
                'verbose_name_plural': "O'qituvchilar dars qaydnomalari",
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
