# Generated by Django 6.1 on 2026-09-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_teacherworklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('naqd', 'Naqd pul'), ('plastik', 'Plastik karta'), ('bank', "Bank hisobi / O'tkazma")], default='naqd', max_length=20, verbose_name="To'lov turi"),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('naqd', 'Naqd pul'), ('plastik', 'Plastik karta'), ('bank', "Bank hisobi / O'tkazma")], default='naqd', max_length=20, verbose_name="To'lov turi"),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='payment_method',
            field=models.CharField(choices=[('naqd', 'Naqd'), ('plastik', 'Plastik'), ('terminal', 'Terminal'), ('bank', "Bank o'tkazmasi")], max_length=20),
        ),
    ]
