# Generated by Django 6.1 on 2026-09-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_expense_payment_method_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesetting',
            name='extra_lesson_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name="Qo'shimcha dars (zamen) 1 soat narxi"),
        ),
    ]
