# Generated by Django 6.1 on 2026-09-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_financesetting_extra_lesson_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbox',
            options={'verbose_name': 'Kassa', 'verbose_name_plural': 'Kassalar'},
        ),
        migrations.AlterModelOptions(
            name='cashtransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kassa amaliyoti', 'verbose_name_plural': 'Kassa amaliyotlari'},
        ),
        migrations.AlterModelOptions(
            name='financeaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Moliya amali (Bonus/Jarima)', 'verbose_name_plural': 'Moliya amallari (Bonus/Jarima)'},
        ),
        migrations.AlterModelOptions(
            name='financesetting',
            options={'verbose_name': 'Moliya sozlamasi', 'verbose_name_plural': 'Moliya sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kassa tranzaksiyasi', 'verbose_name_plural': 'Kassa tranzaksiyalari'},
        ),
    ]
