# Generated by Django 6.1 on 2026-09-11 06:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_remove_building_branch_remove_building_organization_and_more'),
        ('finance', '0014_alter_cashtransaction_date_and_more'),
        ('organizations', '0004_telegramnotificationsetting_support_contact_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherworklog',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='teacherworklog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='teacherworklog',
            name='group',
        ),
        migrations.RemoveField(
            model_name='teacherworklog',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='teacherworklog',
            name='original_teacher',
        ),
        migrations.RemoveField(
            model_name='teacherworklog',
            name='teacher',
        ),
        migrations.AlterModelOptions(
            name='cashtransaction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='financeaction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='financesetting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.AddIndex(
            model_name='cashbox',
            index=models.Index(fields=['organization', 'branch', 'is_archived'], name='finance_cas_organiz_438867_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['organization', 'cashbox', 'date'], name='finance_cas_organiz_9675fe_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['organization', 'transaction_type', 'date'], name='finance_cas_organiz_e9d31a_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['organization', 'created_at'], name='finance_cas_organiz_930633_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['student', 'date'], name='finance_cas_student_2b33e7_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['employee', 'date'], name='finance_cas_employe_c6bc41_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['organization', 'cashbox', 'date'], name='finance_exp_organiz_d8d84d_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['organization', 'date'], name='finance_exp_organiz_193bab_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'student', 'date'], name='finance_pay_organiz_96f15e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'cashbox', 'date'], name='finance_pay_organiz_81d763_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'date'], name='finance_pay_organiz_982f29_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['organization', 'cashbox', 'created_at'], name='finance_tra_organiz_15f4f5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['organization', 'type', 'category'], name='finance_tra_organiz_3c93ae_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['organization', 'created_at'], name='finance_tra_organiz_e2d2e0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['student', 'created_at'], name='finance_tra_student_a5c1af_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['employee', 'created_at'], name='finance_tra_employe_a045fa_idx'),
        ),
        migrations.DeleteModel(
            name='TeacherWorkLog',
        ),
    ]
