# Generated by Django 6.1 on 2026-09-14 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_attendance_unique_student_group_date_attendance_and_more'),
        ('finance', '0015_remove_teacherworklog_branch_and_more'),
        ('organizations', '0004_telegramnotificationsetting_support_contact_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='check_payment_amount_gt_zero'),
        ),
    ]
