# Generated by Django 6.1 on 2026-09-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='1 soat dars narxi (soatbay)'),
        ),
        migrations.AddField(
            model_name='user',
            name='salary_type',
            field=models.CharField(choices=[('percentage', 'Foizli'), ('hourly', 'Soatbay'), ('fixed', "O'zgarmas oylik")], default='percentage', max_length=20, verbose_name='Oylik hisoblash turi'),
        ),
    ]
