# Generated by Django 6.1 on 2026-09-10 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_hourly_rate_user_salary_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqam')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Sessiya tokeni')),
                ('otp_code', models.CharField(max_length=6, verbose_name='6 xonali tasdiqlash kodi')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Telegram orqali tasdiqlanganmi')),
                ('is_used', models.BooleanField(default=False, verbose_name='Parol tiklashda ishlatilganmi')),
                ('attempts', models.IntegerField(default=0, verbose_name='Urinishlar soni')),
                ('expires_at', models.DateTimeField(verbose_name='Amal qilish muddati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Parolni tiklash sessiyasi',
                'verbose_name_plural': 'Parolni tiklash sessiyalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
