# Generated by Django 6.1 on 2026-09-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordresetsession'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('finance', '0014_alter_cashtransaction_date_and_more'),
        ('organizations', '0004_telegramnotificationsetting_support_contact_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'role', 'is_active'], name='accounts_us_organiz_93ee22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'phone'], name='accounts_us_organiz_f10b76_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'branch'], name='accounts_us_organiz_399b34_idx'),
        ),
    ]
