# Generated by Django 6.1 on 2026-09-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lesson_hours',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dars soati'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fan / Mutaxassislik'),
        ),
    ]
