# Generated by Django 6.1 on 2026-09-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weekly_hours',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Haftalik dars soati'),
        ),
    ]
