# Generated by Django 6.1 on 2026-09-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_weekly_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='weekly_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Haftalik dars soati'),
        ),
    ]
