# Generated by Django 6.1 on 2026-09-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_weekly_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fixed_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name="Qat'iy oylik summa (so'm)"),
        ),
    ]
