# Generated by Django 6.1 on 2026-09-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_fixed_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Foizli'), ('hourly', 'Soatbay'), ('fixed', "O'zgarmas oylik"), ('unassigned', 'Belgilanmagan'), ('none', 'Belgilanmagan')], default='percentage', max_length=20, null=True, verbose_name='Oylik hisoblash turi'),
        ),
    ]
