# Generated by Django 6.1 on 2026-09-14 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_salary_type'),
        ('organizations', '0004_telegramnotificationsetting_support_contact_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fan / Mutaxassislik'),
        ),
        migrations.CreateModel(
            name='WeeklyLessonHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nomi / Tavsifi')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Haftalik dars soati')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Haftalik dars soati',
                'verbose_name_plural': 'Haftalik dars soatlari',
                'ordering': ['hours'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_lesson_hour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='accounts.weeklylessonhour', verbose_name="Haftalik dars soati ma'lumotnomasi"),
        ),
    ]
