# Generated by Django 6.1 on 2026-09-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('subscription_expiry', 'Tarif tugashidan oldin'), ('balance_low', 'Balance kam'), ('info', 'Umumiy xabar'), ('birthday_reminder', "Tug'ilgan kun eslatmasi"), ('student_appeal', "O'quvchi murojaati / shikoyati")], default='info', max_length=50),
        ),
    ]
