# Generated by Django 6.1 on 2026-09-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('subscription_expiry', 'Tarif tugashidan oldin'), ('balance_low', 'Balance kam'), ('info', 'Umumiy xabar'), ('birthday_reminder', "Tug'ilgan kun eslatmasi")], default='info', max_length=50),
        ),
    ]
