"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(BASE_DIR / '.env')
# helljsdzfhgbjszdfbgdgfjnhvcfgd
# Quick-start development settings - unsuitable for production
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key')
DEBUG = True

ALLOWED_HOSTS = [
    "smart-backend-dtub.onrender.com",
    "musojon1995.pythonanywhere.com",
    "smartalim.pythonanywhere.com",
    ".pythonanywhere.com",
    "localhost",
    "127.0.0.1",
    "*",
]

CSRF_TRUSTED_ORIGINS = [
    'https://smart-backend-dtub.onrender.com',
    'https://musojon1995.pythonanywhere.com',
    'https://smartalim.pythonanywhere.com',
]


# PythonAnywhere va Render kabi HTTPS proxy'larda redirect loop oldini olish uchun
# ESLATMA: SECURE_PROXY_SSL_HEADER qo'shilmaydi - PythonAnywhere'da session cookie muammo keltirib chiqaradi
SESSION_COOKIE_SECURE = False      # HTTP orqali ham session cookie ishlashi uchun
CSRF_COOKIE_SECURE = False         # HTTP orqali ham CSRF cookie ishlashi uchun
SESSION_COOKIE_SAMESITE = 'Lax'   # Cross-site muammolaridan himoya
CSRF_COOKIE_SAMESITE = 'Lax'      # Cross-site muammolaridan himoya
SESSION_COOKIE_HTTPONLY = True     # JS orqali o'qilmasin
SESSION_SAVE_EVERY_REQUEST = True  # Har so'rovda session saqlanadi

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party packages
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',

    # Local apps
    'organizations',
    'accounts',
    'academics',
    'finance',
    'crm',
    'tasks',
    'audit',
    'communication',
    'billing',
    'drf_spectacular',
    'analytics',
    'support',
    'kpi',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be at the top
    'django.middleware.security.SecurityMiddleware',
    # 'config.middleware.PreservePostRedirectMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# Lokal kompyuterda SQLite ishlaydi, Render serverida esa avtomatik Neon PostgreSQL-ga ulanadi
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # 'ENGINE': 'django.db.backends.postgresql',
        # 'NAME': os.environ.get('DB_NAME'),  # Yangi kompyuterdagi muhitdan o'qiydi
        # 'USER': os.environ.get('DB_USER'),  # O'sha kompyuter foydalanuvchisi
        # 'PASSWORD': os.environ.get('DB_PASSWORD'),  # O'sha kompyuter paroli
        # 'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        # 'PORT': os.environ.get('DB_PORT', '5432'),
        'CONN_MAX_AGE': 600000000000000000,
    }
}

# Faqatgina DATABASE_URL bor bo'lsa VA u postgres:// bilan boshlansa ishlatamiz
db_url = os.getenv('DATABASE_URL')
if db_url and db_url.startswith('postgres://'):
    DATABASES['default'] = dj_database_url.config(conn_max_age=600, ssl_require=True)

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'EXCEPTION_HANDLER': 'config.exception_handler.custom_exception_handler',
}

# SimpleJWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=10000),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=6000),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-branch-id',
    'x-org-id',
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Tashkent'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SPECTACULAR_SETTINGS = {
    'TITLE': 'SmartTalim API',
    'DESCRIPTION': 'SmartTalim Backend API',
    'VERSION': '1.0.0',
}