# Generated by Django 6.1 on 2026-09-11 06:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_remove_building_branch_remove_building_organization_and_more'),
        ('crm', '0001_initial'),
        ('organizations', '0004_telegramnotificationsetting_support_contact_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='crm_lead_pipelin_e68a31_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='crm_lead_source__21714c_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='crm_lead_status_2c1bc7_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='crm_lead_phone_8180e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='crm_lead_name_977dba_idx',
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'branch', 'status'], name='crm_lead_organiz_bc4913_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'phone'], name='crm_lead_organiz_a7d716_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'created_at'], name='crm_lead_organiz_9d83ac_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'pipeline', 'section'], name='crm_lead_organiz_d9b3cd_idx'),
        ),
    ]
