# Generated by Django 6.1 on 2026-08-29 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_studentgroupleave_student_name_and_more'),
        ('organizations', '0004_telegramnotificationsetting_support_contact_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Fan rangi (HEX/RGB)'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol / Nofaol'),
        ),
        migrations.AddField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Topshirish muddati'),
        ),
        migrations.AddField(
            model_name='homework',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Topshiriq tavsifi'),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_homeworks', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi"),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Topshirish sanasi (eski)'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='homeworks/', verbose_name='Biriktirilgan fayl'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='academics.group', verbose_name='Guruh'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Topshiriq tavsifi (eski)'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Mavzu'),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Bino nomi')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Manzili')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name="Sig'imi")),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Bino',
                'verbose_name_plural': 'Binolar',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.O')),
                ('relation', models.CharField(choices=[('father', 'Otasi'), ('mother', 'Onasi'), ('guardian', 'Vasiy'), ('other', 'Boshqa')], default='father', max_length=20, verbose_name='Qarindoshlik darajasi')),
                ('phone', models.CharField(max_length=30, verbose_name='Asosiy telefon')),
                ('extra_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name="Qo'shimcha telefon")),
                ('workplace', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ish joyi / Kasbi')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Manzili')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='academics.student', verbose_name="O'quvchisi")),
            ],
            options={
                'verbose_name': 'Ota-ona',
                'verbose_name_plural': 'Ota-onalar',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_level', models.CharField(max_length=10, verbose_name='Sinf darajasi (masalan: 1, 4, 11)')),
                ('section', models.CharField(max_length=10, verbose_name='Sinf harfi (masalan: A, B, C)')),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Rus'), ('en', 'Ingliz')], default='uz', max_length=10, verbose_name="Ta'lim tili")),
                ('academic_year', models.CharField(default='2026-2027', max_length=20, verbose_name="O'quv yili")),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='academics.room', verbose_name='Biriktirilgan xona')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_classes', to=settings.AUTH_USER_MODEL, verbose_name='Sinf rahbari')),
            ],
            options={
                'verbose_name': 'Sinf',
                'verbose_name_plural': 'Sinflar',
                'unique_together': {('organization', 'branch', 'grade_level', 'section', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StudentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(default='Toshkent shahri', max_length=100, verbose_name='Viloyat / Shahar')),
                ('district', models.CharField(max_length=100, verbose_name='Tuman / Shahar')),
                ('address', models.CharField(max_length=500, verbose_name="To'liq manzil (Ko'cha, uy, xonadon)")),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ota-ona F.I.O')),
                ('parent_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ota-ona telefoni')),
                ('student_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name="O'quvchi telefoni")),
                ('notes', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha izoh")),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_info', to='academics.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "O'quvchi manzili",
                'verbose_name_plural': "O'quvchilar manzillari",
            },
        ),
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_classes', to='academics.student')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.schoolclass')),
            ],
            options={
                'verbose_name': "Sinf o'quvchisi",
                'verbose_name_plural': "Sinf o'quvchilari",
                'unique_together': {('school_class', 'student')},
            },
        ),
    ]
