# Generated by Django 6.1 on 2026-08-29 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_course_color_course_is_active_homework_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_list', to='academics.schoolclass', verbose_name='Sinfi'),
        ),
        migrations.AlterField(
            model_name='studentfieldsetting',
            name='field_name',
            field=models.CharField(choices=[('last_name', 'Familiya'), ('email', 'Elektron pochta'), ('photo', 'Rasm'), ('category', 'Kategoriya'), ('birth_date', "Tug'ilgan sana"), ('application', "So'rovnoma"), ('language', 'Til'), ('payment_date', "To'lov sanasi"), ('address', 'Uy manzili'), ('target_university', 'Maqsad qilgan universitet'), ('school_class', 'Sinf'), ('organization', 'Tashkilot'), ('father_name', 'Otasining ismi'), ('father_phone', 'Otasining telefon raqami'), ('father_email', 'Otasining elektron pochtasi'), ('mother_name', 'Onasining ismi'), ('mother_phone', 'Onasining telefon raqami'), ('mother_email', 'Onasining elektron pochtasi')], max_length=100),
        ),
    ]
