# Generated by Django 6.1 on 2026-09-03 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_student_school_class_and_more'),
        ('organizations', '0004_telegramnotificationsetting_support_contact_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appeal_type', models.CharField(choices=[('complaint', 'Shikoyat'), ('suggestion', 'Taklif'), ('request', 'Talab / Ariza'), ('other', 'Boshqa')], default='complaint', max_length=50, verbose_name='Murojaat turi')),
                ('message', models.TextField(verbose_name='Murojaat matni')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda (Qabul qilinmagan)'), ('in_progress', "Ko'rib chiqilmoqda (Qabul qilingan)"), ('resolved', 'Hal etildi'), ('rejected', 'Rad etildi')], default='pending', max_length=50, verbose_name='Holati')),
                ('response', models.TextField(blank=True, null=True, verbose_name="Ma'muriyat javobi")),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Javob berilgan vaqt')),
                ('is_escalated_to_owner', models.BooleanField(default=False, verbose_name='Tashkilot egasiga hisobot bot orqali yuborilgan')),
                ('escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='Egasiga yuborilgan vaqt')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_appeals', to=settings.AUTH_USER_MODEL, verbose_name='Javob bergan xodim')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='academics.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "O'quvchi murojaati",
                'verbose_name_plural': "O'quvchilar murojaatlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
