# Generated by Django 6.1 on 2026-09-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_studentappeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentappeal',
            name='satisfaction_poll_sent',
            field=models.BooleanField(default=False, verbose_name="3 kunlik qoniqish so'rovi talabaga yuborilgan"),
        ),
        migrations.AddField(
            model_name='studentappeal',
            name='satisfaction_poll_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Qoniqish so'rovi yuborilgan vaqt"),
        ),
        migrations.AddField(
            model_name='studentappeal',
            name='satisfaction_responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Talaba javob bergan vaqt'),
        ),
        migrations.AddField(
            model_name='studentappeal',
            name='student_satisfied',
            field=models.BooleanField(blank=True, null=True, verbose_name="Talaba muammo hal bo'lganini tasdiqladi (True=Ha, False=Yo'q)"),
        ),
    ]
