# Generated by Django 6.1 on 2026-09-11 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_studentappeal_satisfaction_poll_sent_and_more'),
        ('organizations', '0004_telegramnotificationsetting_support_contact_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='building',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='classstudent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='classstudent',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='classstudent',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='classstudent',
            name='school_class',
        ),
        migrations.RemoveField(
            model_name='classstudent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='room',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_class',
        ),
        migrations.RemoveField(
            model_name='studentaddress',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='studentaddress',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='studentaddress',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentappeal',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='studentappeal',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='studentappeal',
            name='responded_by',
        ),
        migrations.RemoveField(
            model_name='studentappeal',
            name='student',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='description',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='group_homeworks/files/'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='academics.group'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentfieldsetting',
            name='field_name',
            field=models.CharField(choices=[('last_name', 'Familiya'), ('email', 'Elektron pochta'), ('photo', 'Rasm'), ('category', 'Kategoriya'), ('birth_date', "Tug'ilgan sana"), ('application', "So'rovnoma"), ('language', 'Til'), ('payment_date', "To'lov sanasi"), ('address', 'Uy manzili'), ('target_university', 'Maqsad qilgan universitet'), ('organization', 'Tashkilot'), ('father_name', 'Otasining ismi'), ('father_phone', 'Otasining telefon raqami'), ('father_email', 'Otasining elektron pochtasi'), ('mother_name', 'Onasining ismi'), ('mother_phone', 'Onasining telefon raqami'), ('mother_email', 'Onasining elektron pochtasi')], max_length=100),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['organization', 'group', 'date'], name='academics_a_organiz_fa8171_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='academics_a_student_ec0522_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['group', 'date', 'status'], name='academics_a_group_i_a71289_idx'),
        ),
        migrations.AddIndex(
            model_name='balancehistory',
            index=models.Index(fields=['organization', 'student', 'date'], name='academics_b_organiz_e22507_idx'),
        ),
        migrations.AddIndex(
            model_name='balancehistory',
            index=models.Index(fields=['student', 'date'], name='academics_b_student_f58272_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['organization', 'branch', 'status'], name='academics_g_organiz_80f09d_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['course', 'status'], name='academics_g_course__3febd8_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['teacher', 'status'], name='academics_g_teacher_b34a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['organization', 'created_at'], name='academics_g_organiz_50db5d_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['organization', 'branch', 'is_archived'], name='academics_s_organiz_893048_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['organization', 'phone'], name='academics_s_organiz_a4abf5_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['organization', 'balance'], name='academics_s_organiz_c48fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['organization', 'created_at'], name='academics_s_organiz_9605b9_idx'),
        ),
        migrations.AddIndex(
            model_name='studentgroup',
            index=models.Index(fields=['organization', 'group', 'student'], name='academics_s_organiz_ca9279_idx'),
        ),
        migrations.AddIndex(
            model_name='studentgroup',
            index=models.Index(fields=['student', 'group'], name='academics_s_student_be50ef_idx'),
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='ClassStudent',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='SchoolClass',
        ),
        migrations.DeleteModel(
            name='StudentAddress',
        ),
        migrations.DeleteModel(
            name='StudentAppeal',
        ),
    ]
