# Generated by Django 6.1 on 2026-09-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_remove_building_branch_remove_building_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancehistory',
            name='transaction_type',
            field=models.CharField(max_length=255),
        ),
    ]
