# Generated by Django 6.1 on 2026-09-13 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_alter_balancehistory_transaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Sinf', 'verbose_name_plural': 'Sinflar'},
        ),
        migrations.AlterModelOptions(
            name='groupteacher',
            options={'verbose_name': "Sinf o'qituvchisi", 'verbose_name_plural': "Sinf o'qituvchilari"},
        ),
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'verbose_name': "Sinf o'quvchisi", 'verbose_name_plural': "Sinf o'quvchilari"},
        ),
        migrations.AddField(
            model_name='group',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='grade_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='language',
            field=models.CharField(blank=True, default='uz', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='academics.course'),
        ),
    ]
