# Generated by Django 6.1 on 2026-09-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_alter_group_options_alter_groupteacher_options_and_more'),
        ('organizations', '0004_telegramnotificationsetting_support_contact_link'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'group', 'date'), name='unique_student_group_date_attendance'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='unique_exam_student_result'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='check_exam_result_score_range'),
        ),
        migrations.AddConstraint(
            model_name='studentgroup',
            constraint=models.UniqueConstraint(fields=('student', 'group'), name='unique_student_group'),
        ),
    ]
